abbr -a lf 'ls -Flah'
abbr -a yr 'cal -y'
abbr -a g git
abbr -a gs 'git status -sb'
abbr -a gc 'git checkout'
abbr -a ga 'git add -p'
abbr -a gah 'git stash; and git pull --rebase; and git stash pop'
abbr -a grau 'git remote update'
abbr -a kbs 'keybase chat send'
abbr -a kbr 'keybase chat read'
abbr -a kbl 'keybase chat list'
abbr -a pr 'gh pr create -t (git show -s --format=%s HEAD) -b (git show -s --format=%B HEAD | tail -n+3)'
abbr -a c. 'code -n .'

# kubectl abbr
abbr -a k kubectl
abbr -a kaf 'kubectl apply -f'
abbr -a kca '_kca(){ kubectl "$@" --all-namespaces;  unset -f _kca; }; _kca'
abbr -a kccc 'kubectl config current-context'
abbr -a kcdc 'kubectl config delete-context'
abbr -a kcgc 'kubectl config get-contexts'
abbr -a kcn 'kubectl config set-context --current --namespace'
abbr -a kcp 'kubectl cp'
abbr -a kcsc 'kubectl config set-context'
abbr -a kcuc 'kubectl config use-context'
abbr -a kdcj 'kubectl describe cronjob'
abbr -a kdcm 'kubectl describe configmap'
abbr -a kdd 'kubectl describe deployment'
abbr -a kdds 'kubectl describe daemonset'
abbr -a kdel 'kubectl delete'
abbr -a kdelcj 'kubectl delete cronjob'
abbr -a kdelcm 'kubectl delete configmap'
abbr -a kdeld 'kubectl delete deployment'
abbr -a kdelds 'kubectl delete daemonset'
abbr -a kdelf 'kubectl delete -f'
abbr -a kdeli 'kubectl delete ingress'
abbr -a kdelno 'kubectl delete node'
abbr -a kdelns 'kubectl delete namespace'
abbr -a kdelp 'kubectl delete pods'
abbr -a kdelpvc 'kubectl delete pvc'
abbr -a kdels 'kubectl delete svc'
abbr -a kdelsa 'kubectl delete sa'
abbr -a kdelsec 'kubectl delete secret'
abbr -a kdelss 'kubectl delete statefulset'
abbr -a kdi 'kubectl describe ingress'
abbr -a kdno 'kubectl describe node'
abbr -a kdns 'kubectl describe namespace'
abbr -a kdp 'kubectl describe pods'
abbr -a kdpvc 'kubectl describe pvc'
abbr -a kds 'kubectl describe svc'
abbr -a kdsa 'kubectl describe sa'
abbr -a kdsec 'kubectl describe secret'
abbr -a kdss 'kubectl describe statefulset'
abbr -a kecj 'kubectl edit cronjob'
abbr -a kecm 'kubectl edit configmap'
abbr -a ked 'kubectl edit deployment'
abbr -a keds 'kubectl edit daemonset'
abbr -a kei 'kubectl edit ingress'
abbr -a keno 'kubectl edit node'
abbr -a kens 'kubectl edit namespace'
abbr -a kep 'kubectl edit pods'
abbr -a kepvc 'kubectl edit pvc'
abbr -a kes 'kubectl edit svc'
abbr -a kess 'kubectl edit statefulset'
abbr -a keti 'kubectl exec -ti'
abbr -a kga 'kubectl get all'
abbr -a kgaa 'kubectl get all --all-namespaces'
abbr -a kgcj 'kubectl get cronjob'
abbr -a kgcm 'kubectl get configmaps'
abbr -a kgcma 'kubectl get configmaps --all-namespaces'
abbr -a kgd 'kubectl get deployment'
abbr -a kgda 'kubectl get deployment --all-namespaces'
abbr -a kgds 'kubectl get daemonset'
abbr -a kgi 'kubectl get ingress'
abbr -a kgia 'kubectl get ingress --all-namespaces'
abbr -a kgno 'kubectl get nodes'
abbr -a kgns 'kubectl get namespaces'
abbr -a kgp 'kubectl get pods'
abbr -a kgpa 'kubectl get pods --all-namespaces'
abbr -a kgpvc 'kubectl get pvc'
abbr -a kgpvca 'kubectl get pvc --all-namespaces'
abbr -a kgrs 'kubectl get rs'
abbr -a kgs 'kubectl get svc'
abbr -a kgsa 'kubectl get sa'
abbr -a kgsec 'kubectl get secret'
abbr -a kgseca 'kubectl get secret --all-namespaces'
abbr -a kgss 'kubectl get statefulset'
abbr -a kgssa 'kubectl get statefulset --all-namespaces'
abbr -a kl 'kubectl logs'
abbr -a kl1h 'kubectl logs --since 1h'
abbr -a kl1m 'kubectl logs --since 1m'
abbr -a kl1s 'kubectl logs --since 1s'
abbr -a klf 'kubectl logs -f'
abbr -a klf1h 'kubectl logs --since 1h -f'
abbr -a klf1m 'kubectl logs --since 1m -f'
abbr -a klf1s 'kubectl logs --since 1s -f'
abbr -a kpf 'kubectl port-forward'
abbr -a krh 'kubectl rollout history'
abbr -a krsd 'kubectl rollout status deployment'
abbr -a krsss 'kubectl rollout status statefulset'
abbr -a kru 'kubectl rollout undo'
abbr -a ksd 'kubectl scale deployment'
abbr -a ksss 'kubectl scale statefulset'
